apiVersion: "pipelinesascode.tekton.dev/v1alpha1"
kind: Repository
metadata:
  name: e32fniw0f-dotnet-basic-repository
spec:
  url: https://github.com/rhtap-test-organization-jk/e32fniw0f-dotnet-basic